# >>>  > ------------------ <  <<<
# >>>      NCode-AFKZone       <<<
# >>>   by Sajen (dc: sajen)   <<<
# >>>  > ------------------ <  <<<

afk:
  afk-messages:
    message-type: title
    reward-give-title: "&a&lAFK"
    reward-give-subtitle: "&7Właśnie otrzymałeś nagrodę za przebywanie na strefie AFK"
    reward-give-actionbar: "&a&lAFK &8| &7Właśnie otrzymałeś nagrodę za przebywanie na strefie AFK"
    reward-give-message: "&a&lAFK &8| &7Właśnie otrzymałeś nagrodę za przebywanie na strefie AFK"
  afk-other-things:
    # Nazwa regionu Strefy AFK
    afk-region: afk
    # Czas co jaki ma dawać nagrodę (w sekundach)
    afk-reward-time: 60
    # Komendy wykonywane za przebywanie w strefie AFK
    # Można wpisać dowolną liczbę komend
    # {PLAYER} - nick gracza
    afk-command-rewards:
      - give {PLAYER} diamond 1
      - lp user {PLAYER} parent addtemp vip 7d